// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const markAppHeartbeatsFirstReceived = `-- name: MarkAppHeartbeatsFirstReceived :exec
UPDATE app
SET heartbeats_first_received_at = $2
WHERE id = $1
  AND heartbeats_first_received_at IS NULL
`

type MarkAppHeartbeatsFirstReceivedParams struct {
	ID                        string           `json:"id"`
	HeartbeatsFirstReceivedAt pgtype.Timestamp `json:"heartbeats_first_received_at"`
}

func (q *Queries) MarkAppHeartbeatsFirstReceived(ctx context.Context, arg MarkAppHeartbeatsFirstReceivedParams) error {
	_, err := q.db.Exec(ctx, markAppHeartbeatsFirstReceived, arg.ID, arg.HeartbeatsFirstReceivedAt)
	return err
}

const markAppLogsFirstReceived = `-- name: MarkAppLogsFirstReceived :exec
UPDATE app
SET logs_first_received_at = NOW()
WHERE id = $1
  AND logs_first_received_at IS NULL
`

func (q *Queries) MarkAppLogsFirstReceived(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAppLogsFirstReceived, id)
	return err
}

const markAppMetricsFirstReceived = `-- name: MarkAppMetricsFirstReceived :exec
UPDATE app
SET metrics_first_received_at = NOW()
WHERE id = $1
  AND metrics_first_received_at IS NULL
`

func (q *Queries) MarkAppMetricsFirstReceived(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAppMetricsFirstReceived, id)
	return err
}

const markAppTracesFirstReceived = `-- name: MarkAppTracesFirstReceived :exec
UPDATE app
SET traces_first_received_at = NOW()
WHERE id = $1
  AND traces_first_received_at IS NULL
`

func (q *Queries) MarkAppTracesFirstReceived(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markAppTracesFirstReceived, id)
	return err
}
