// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationUsage = `-- name: CreateOrganizationUsage :one
INSERT INTO organization_usage (
  id,
  organization_id,
  logs_retention_days,
  traces_retention_days,
  metrics_retention_days,
  current_period_start,
  current_period_end,
  ingest_limit_bytes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
  id,
  organization_id,
  logs_retention_days,
  traces_retention_days,
  metrics_retention_days,
  current_period_start,
  current_period_end,
  logs_ingested_bytes,
  traces_ingested_bytes,
  metrics_ingested_bytes,
  ingest_limit_bytes,
  notified_70_at,
  notified_85_at,
  notified_100_at,
  created_at,
  updated_at
`

type CreateOrganizationUsageParams struct {
	ID                   string           `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	LogsRetentionDays    int32            `json:"logs_retention_days"`
	TracesRetentionDays  int32            `json:"traces_retention_days"`
	MetricsRetentionDays int32            `json:"metrics_retention_days"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	IngestLimitBytes     int64            `json:"ingest_limit_bytes"`
}

func (q *Queries) CreateOrganizationUsage(ctx context.Context, arg CreateOrganizationUsageParams) (OrganizationUsage, error) {
	row := q.db.QueryRow(ctx, createOrganizationUsage,
		arg.ID,
		arg.OrganizationID,
		arg.LogsRetentionDays,
		arg.TracesRetentionDays,
		arg.MetricsRetentionDays,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.IngestLimitBytes,
	)
	var i OrganizationUsage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LogsRetentionDays,
		&i.TracesRetentionDays,
		&i.MetricsRetentionDays,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LogsIngestedBytes,
		&i.TracesIngestedBytes,
		&i.MetricsIngestedBytes,
		&i.IngestLimitBytes,
		&i.Notified70At,
		&i.Notified85At,
		&i.Notified100At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppRetentionPolicy = `-- name: GetAppRetentionPolicy :one
SELECT
  app.organization_id,
  COALESCE(organization.billing_plan::text, ''::text)::text AS plan_key,
  CASE WHEN organization.billing_plan IS NULL THEN 'default' ELSE 'billing' END::text AS source,
  COALESCE(organization_usage.logs_retention_days, $2::integer) AS logs_retention_days,
  COALESCE(organization_usage.traces_retention_days, $3::integer) AS traces_retention_days,
  COALESCE(organization_usage.metrics_retention_days, $4::integer) AS metrics_retention_days,
  organization_usage.ingest_limit_bytes AS logs_max_ingest_bytes_per_period,
  organization_usage.ingest_limit_bytes AS traces_max_ingest_bytes_per_period,
  organization_usage.ingest_limit_bytes AS metrics_max_ingest_bytes_per_period
FROM app
JOIN organization ON organization.id = app.organization_id
LEFT JOIN organization_usage ON organization_usage.organization_id = organization.id
WHERE app.id = $1
`

type GetAppRetentionPolicyParams struct {
	ID                          string `json:"id"`
	DefaultLogsRetentionDays    int32  `json:"default_logs_retention_days"`
	DefaultTracesRetentionDays  int32  `json:"default_traces_retention_days"`
	DefaultMetricsRetentionDays int32  `json:"default_metrics_retention_days"`
}

type GetAppRetentionPolicyRow struct {
	OrganizationID                 string      `json:"organization_id"`
	PlanKey                        string      `json:"plan_key"`
	Source                         string      `json:"source"`
	LogsRetentionDays              int32       `json:"logs_retention_days"`
	TracesRetentionDays            int32       `json:"traces_retention_days"`
	MetricsRetentionDays           int32       `json:"metrics_retention_days"`
	LogsMaxIngestBytesPerPeriod    pgtype.Int8 `json:"logs_max_ingest_bytes_per_period"`
	TracesMaxIngestBytesPerPeriod  pgtype.Int8 `json:"traces_max_ingest_bytes_per_period"`
	MetricsMaxIngestBytesPerPeriod pgtype.Int8 `json:"metrics_max_ingest_bytes_per_period"`
}

func (q *Queries) GetAppRetentionPolicy(ctx context.Context, arg GetAppRetentionPolicyParams) (GetAppRetentionPolicyRow, error) {
	row := q.db.QueryRow(ctx, getAppRetentionPolicy,
		arg.ID,
		arg.DefaultLogsRetentionDays,
		arg.DefaultTracesRetentionDays,
		arg.DefaultMetricsRetentionDays,
	)
	var i GetAppRetentionPolicyRow
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanKey,
		&i.Source,
		&i.LogsRetentionDays,
		&i.TracesRetentionDays,
		&i.MetricsRetentionDays,
		&i.LogsMaxIngestBytesPerPeriod,
		&i.TracesMaxIngestBytesPerPeriod,
		&i.MetricsMaxIngestBytesPerPeriod,
	)
	return i, err
}

const getBillingState = `-- name: GetBillingState :one
SELECT
  COALESCE(organization.billing_plan::text, current_subscription.plan, 'none') AS plan_key,
  COALESCE(organization.billing_status::text, current_subscription.status, 'inactive') AS status,
  COALESCE(organization_usage.ingest_limit_bytes, 0) AS included_bytes,
  COALESCE(organization_usage.current_period_start, current_subscription.period_start) AS period_start,
  COALESCE(organization_usage.current_period_end, current_subscription.period_end) AS period_end
FROM organization
LEFT JOIN organization_usage ON organization_usage.organization_id = organization.id
LEFT JOIN LATERAL (
  SELECT plan, status, period_start, period_end
  FROM subscription
  WHERE reference_id = $1
  ORDER BY
    CASE status
      WHEN 'active' THEN 0
      WHEN 'trialing' THEN 1
      WHEN 'paused' THEN 2
      WHEN 'past_due' THEN 3
      WHEN 'unpaid' THEN 4
      WHEN 'incomplete' THEN 5
      ELSE 6
    END,
    period_end DESC
  LIMIT 1
) AS current_subscription ON TRUE
WHERE organization.id = $1
`

type GetBillingStateRow struct {
	PlanKey       string           `json:"plan_key"`
	Status        string           `json:"status"`
	IncludedBytes int64            `json:"included_bytes"`
	PeriodStart   pgtype.Timestamp `json:"period_start"`
	PeriodEnd     pgtype.Timestamp `json:"period_end"`
}

func (q *Queries) GetBillingState(ctx context.Context, referenceID string) (GetBillingStateRow, error) {
	row := q.db.QueryRow(ctx, getBillingState, referenceID)
	var i GetBillingStateRow
	err := row.Scan(
		&i.PlanKey,
		&i.Status,
		&i.IncludedBytes,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getOrganizationUsageForUpdate = `-- name: GetOrganizationUsageForUpdate :one
SELECT
  id,
  organization_id,
  logs_retention_days,
  traces_retention_days,
  metrics_retention_days,
  current_period_start,
  current_period_end,
  logs_ingested_bytes,
  traces_ingested_bytes,
  metrics_ingested_bytes,
  ingest_limit_bytes,
  notified_70_at,
  notified_85_at,
  notified_100_at,
  created_at,
  updated_at
FROM organization_usage
WHERE organization_id = $1
FOR UPDATE
`

func (q *Queries) GetOrganizationUsageForUpdate(ctx context.Context, organizationID string) (OrganizationUsage, error) {
	row := q.db.QueryRow(ctx, getOrganizationUsageForUpdate, organizationID)
	var i OrganizationUsage
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LogsRetentionDays,
		&i.TracesRetentionDays,
		&i.MetricsRetentionDays,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.LogsIngestedBytes,
		&i.TracesIngestedBytes,
		&i.MetricsIngestedBytes,
		&i.IngestLimitBytes,
		&i.Notified70At,
		&i.Notified85At,
		&i.Notified100At,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseOrganizationUsageLogs = `-- name: ReleaseOrganizationUsageLogs :exec
UPDATE organization_usage
SET logs_ingested_bytes = GREATEST(logs_ingested_bytes - $2, 0),
    updated_at = NOW()
WHERE organization_id = $1
`

type ReleaseOrganizationUsageLogsParams struct {
	OrganizationID    string `json:"organization_id"`
	LogsIngestedBytes int64  `json:"logs_ingested_bytes"`
}

func (q *Queries) ReleaseOrganizationUsageLogs(ctx context.Context, arg ReleaseOrganizationUsageLogsParams) error {
	_, err := q.db.Exec(ctx, releaseOrganizationUsageLogs, arg.OrganizationID, arg.LogsIngestedBytes)
	return err
}

const releaseOrganizationUsageMetrics = `-- name: ReleaseOrganizationUsageMetrics :exec
UPDATE organization_usage
SET metrics_ingested_bytes = GREATEST(metrics_ingested_bytes - $2, 0),
    updated_at = NOW()
WHERE organization_id = $1
`

type ReleaseOrganizationUsageMetricsParams struct {
	OrganizationID       string `json:"organization_id"`
	MetricsIngestedBytes int64  `json:"metrics_ingested_bytes"`
}

func (q *Queries) ReleaseOrganizationUsageMetrics(ctx context.Context, arg ReleaseOrganizationUsageMetricsParams) error {
	_, err := q.db.Exec(ctx, releaseOrganizationUsageMetrics, arg.OrganizationID, arg.MetricsIngestedBytes)
	return err
}

const releaseOrganizationUsageTraces = `-- name: ReleaseOrganizationUsageTraces :exec
UPDATE organization_usage
SET traces_ingested_bytes = GREATEST(traces_ingested_bytes - $2, 0),
    updated_at = NOW()
WHERE organization_id = $1
`

type ReleaseOrganizationUsageTracesParams struct {
	OrganizationID      string `json:"organization_id"`
	TracesIngestedBytes int64  `json:"traces_ingested_bytes"`
}

func (q *Queries) ReleaseOrganizationUsageTraces(ctx context.Context, arg ReleaseOrganizationUsageTracesParams) error {
	_, err := q.db.Exec(ctx, releaseOrganizationUsageTraces, arg.OrganizationID, arg.TracesIngestedBytes)
	return err
}

const updateOrganizationUsageLogs = `-- name: UpdateOrganizationUsageLogs :exec
UPDATE organization_usage
SET logs_ingested_bytes = $3,
    ingest_limit_bytes = $4,
    notified_70_at = $5,
    notified_85_at = $6,
    notified_100_at = $7,
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
`

type UpdateOrganizationUsageLogsParams struct {
	ID                string           `json:"id"`
	OrganizationID    string           `json:"organization_id"`
	LogsIngestedBytes int64            `json:"logs_ingested_bytes"`
	IngestLimitBytes  int64            `json:"ingest_limit_bytes"`
	Notified70At      pgtype.Timestamp `json:"notified_70_at"`
	Notified85At      pgtype.Timestamp `json:"notified_85_at"`
	Notified100At     pgtype.Timestamp `json:"notified_100_at"`
}

func (q *Queries) UpdateOrganizationUsageLogs(ctx context.Context, arg UpdateOrganizationUsageLogsParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationUsageLogs,
		arg.ID,
		arg.OrganizationID,
		arg.LogsIngestedBytes,
		arg.IngestLimitBytes,
		arg.Notified70At,
		arg.Notified85At,
		arg.Notified100At,
	)
	return err
}

const updateOrganizationUsageMetrics = `-- name: UpdateOrganizationUsageMetrics :exec
UPDATE organization_usage
SET metrics_ingested_bytes = $3,
    ingest_limit_bytes = $4,
    notified_70_at = $5,
    notified_85_at = $6,
    notified_100_at = $7,
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
`

type UpdateOrganizationUsageMetricsParams struct {
	ID                   string           `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	MetricsIngestedBytes int64            `json:"metrics_ingested_bytes"`
	IngestLimitBytes     int64            `json:"ingest_limit_bytes"`
	Notified70At         pgtype.Timestamp `json:"notified_70_at"`
	Notified85At         pgtype.Timestamp `json:"notified_85_at"`
	Notified100At        pgtype.Timestamp `json:"notified_100_at"`
}

func (q *Queries) UpdateOrganizationUsageMetrics(ctx context.Context, arg UpdateOrganizationUsageMetricsParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationUsageMetrics,
		arg.ID,
		arg.OrganizationID,
		arg.MetricsIngestedBytes,
		arg.IngestLimitBytes,
		arg.Notified70At,
		arg.Notified85At,
		arg.Notified100At,
	)
	return err
}

const updateOrganizationUsageTraces = `-- name: UpdateOrganizationUsageTraces :exec
UPDATE organization_usage
SET traces_ingested_bytes = $3,
    ingest_limit_bytes = $4,
    notified_70_at = $5,
    notified_85_at = $6,
    notified_100_at = $7,
    updated_at = NOW()
WHERE id = $1
  AND organization_id = $2
`

type UpdateOrganizationUsageTracesParams struct {
	ID                  string           `json:"id"`
	OrganizationID      string           `json:"organization_id"`
	TracesIngestedBytes int64            `json:"traces_ingested_bytes"`
	IngestLimitBytes    int64            `json:"ingest_limit_bytes"`
	Notified70At        pgtype.Timestamp `json:"notified_70_at"`
	Notified85At        pgtype.Timestamp `json:"notified_85_at"`
	Notified100At       pgtype.Timestamp `json:"notified_100_at"`
}

func (q *Queries) UpdateOrganizationUsageTraces(ctx context.Context, arg UpdateOrganizationUsageTracesParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationUsageTraces,
		arg.ID,
		arg.OrganizationID,
		arg.TracesIngestedBytes,
		arg.IngestLimitBytes,
		arg.Notified70At,
		arg.Notified85At,
		arg.Notified100At,
	)
	return err
}
