// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deployments.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertDeployment = `-- name: InsertDeployment :exec
INSERT INTO deployment (
  id,
  app_id,
  service_name,
  environment_name,
  version,
  status,
  started_at,
  finished_at,
  git_sha,
  git_branch,
  git_repository,
  git_actor,
  commit_message,
  external_url,
  metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
`

type InsertDeploymentParams struct {
	ID              string           `json:"id"`
	AppID           string           `json:"app_id"`
	ServiceName     string           `json:"service_name"`
	EnvironmentName string           `json:"environment_name"`
	Version         pgtype.Text      `json:"version"`
	Status          DeploymentStatus `json:"status"`
	StartedAt       pgtype.Timestamp `json:"started_at"`
	FinishedAt      pgtype.Timestamp `json:"finished_at"`
	GitSha          pgtype.Text      `json:"git_sha"`
	GitBranch       pgtype.Text      `json:"git_branch"`
	GitRepository   pgtype.Text      `json:"git_repository"`
	GitActor        pgtype.Text      `json:"git_actor"`
	CommitMessage   pgtype.Text      `json:"commit_message"`
	ExternalUrl     pgtype.Text      `json:"external_url"`
	Metadata        []byte           `json:"metadata"`
}

func (q *Queries) InsertDeployment(ctx context.Context, arg InsertDeploymentParams) error {
	_, err := q.db.Exec(ctx, insertDeployment,
		arg.ID,
		arg.AppID,
		arg.ServiceName,
		arg.EnvironmentName,
		arg.Version,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.GitSha,
		arg.GitBranch,
		arg.GitRepository,
		arg.GitActor,
		arg.CommitMessage,
		arg.ExternalUrl,
		arg.Metadata,
	)
	return err
}

const updateDeployment = `-- name: UpdateDeployment :execrows
UPDATE deployment
SET
  status = COALESCE($3::deployment_status, status),
  finished_at = COALESCE($4, finished_at),
  external_url = COALESCE($5, external_url),
  metadata = COALESCE($6, metadata)
WHERE id = $1
  AND app_id = $2
`

type UpdateDeploymentParams struct {
	ID          string               `json:"id"`
	AppID       string               `json:"app_id"`
	Status      NullDeploymentStatus `json:"status"`
	FinishedAt  pgtype.Timestamp     `json:"finished_at"`
	ExternalUrl pgtype.Text          `json:"external_url"`
	Metadata    []byte               `json:"metadata"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeployment,
		arg.ID,
		arg.AppID,
		arg.Status,
		arg.FinishedAt,
		arg.ExternalUrl,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
