// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: heartbeats.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHeartbeatMonitorByToken = `-- name: GetHeartbeatMonitorByToken :one
SELECT
  heartbeat_monitor.id,
  heartbeat_monitor.app_id
FROM heartbeat_monitor
WHERE heartbeat_monitor.token = $1
`

type GetHeartbeatMonitorByTokenRow struct {
	ID    string `json:"id"`
	AppID string `json:"app_id"`
}

func (q *Queries) GetHeartbeatMonitorByToken(ctx context.Context, token string) (GetHeartbeatMonitorByTokenRow, error) {
	row := q.db.QueryRow(ctx, getHeartbeatMonitorByToken, token)
	var i GetHeartbeatMonitorByTokenRow
	err := row.Scan(&i.ID, &i.AppID)
	return i, err
}

const markHeartbeatMonitorHealthy = `-- name: MarkHeartbeatMonitorHealthy :exec
UPDATE heartbeat_monitor
SET
  last_check_in_at = $2,
  status = 'healthy',
  updated_at = $2
WHERE id = $1
`

type MarkHeartbeatMonitorHealthyParams struct {
	ID            string           `json:"id"`
	LastCheckInAt pgtype.Timestamp `json:"last_check_in_at"`
}

func (q *Queries) MarkHeartbeatMonitorHealthy(ctx context.Context, arg MarkHeartbeatMonitorHealthyParams) error {
	_, err := q.db.Exec(ctx, markHeartbeatMonitorHealthy, arg.ID, arg.LastCheckInAt)
	return err
}
