// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ingestion-keys.sql

package pgdb

import (
	"context"
)

const getActiveIngestionKeyByKey = `-- name: GetActiveIngestionKeyByKey :one
SELECT
  ingestion_key.id AS ingestion_key_id,
  app.organization_id,
  ingestion_key.app_id,
  ingestion_key.kind::text AS kind
FROM ingestion_key
JOIN app ON app.id = ingestion_key.app_id
WHERE ingestion_key.key = $1
  AND ingestion_key.revoked_at IS NULL
`

type GetActiveIngestionKeyByKeyRow struct {
	IngestionKeyID string `json:"ingestion_key_id"`
	OrganizationID string `json:"organization_id"`
	AppID          string `json:"app_id"`
	Kind           string `json:"kind"`
}

func (q *Queries) GetActiveIngestionKeyByKey(ctx context.Context, key string) (GetActiveIngestionKeyByKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveIngestionKeyByKey, key)
	var i GetActiveIngestionKeyByKeyRow
	err := row.Scan(
		&i.IngestionKeyID,
		&i.OrganizationID,
		&i.AppID,
		&i.Kind,
	)
	return i, err
}

const touchIngestionKeyLastUsed = `-- name: TouchIngestionKeyLastUsed :exec
UPDATE ingestion_key
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchIngestionKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchIngestionKeyLastUsed, id)
	return err
}
