// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgdb

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlertComparator string

const (
	AlertComparatorGt  AlertComparator = "gt"
	AlertComparatorGte AlertComparator = "gte"
	AlertComparatorLt  AlertComparator = "lt"
	AlertComparatorLte AlertComparator = "lte"
)

func (e *AlertComparator) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertComparator(s)
	case string:
		*e = AlertComparator(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertComparator: %T", src)
	}
	return nil
}

type NullAlertComparator struct {
	AlertComparator AlertComparator `json:"alert_comparator"`
	Valid           bool            `json:"valid"` // Valid is true if AlertComparator is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertComparator) Scan(value interface{}) error {
	if value == nil {
		ns.AlertComparator, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertComparator.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertComparator) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertComparator), nil
}

type AlertDeliveryStatus string

const (
	AlertDeliveryStatusPending   AlertDeliveryStatus = "pending"
	AlertDeliveryStatusSucceeded AlertDeliveryStatus = "succeeded"
	AlertDeliveryStatusFailed    AlertDeliveryStatus = "failed"
)

func (e *AlertDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertDeliveryStatus(s)
	case string:
		*e = AlertDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertDeliveryStatus: %T", src)
	}
	return nil
}

type NullAlertDeliveryStatus struct {
	AlertDeliveryStatus AlertDeliveryStatus `json:"alert_delivery_status"`
	Valid               bool                `json:"valid"` // Valid is true if AlertDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertDeliveryStatus), nil
}

type AlertEventType string

const (
	AlertEventTypeOpened     AlertEventType = "opened"
	AlertEventTypeRenotified AlertEventType = "renotified"
	AlertEventTypeResolved   AlertEventType = "resolved"
	AlertEventTypeTest       AlertEventType = "test"
)

func (e *AlertEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertEventType(s)
	case string:
		*e = AlertEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertEventType: %T", src)
	}
	return nil
}

type NullAlertEventType struct {
	AlertEventType AlertEventType `json:"alert_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if AlertEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertEventType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertEventType), nil
}

type AlertIncidentEntityType string

const (
	AlertIncidentEntityTypeApp       AlertIncidentEntityType = "app"
	AlertIncidentEntityTypeHost      AlertIncidentEntityType = "host"
	AlertIncidentEntityTypeContainer AlertIncidentEntityType = "container"
)

func (e *AlertIncidentEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertIncidentEntityType(s)
	case string:
		*e = AlertIncidentEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertIncidentEntityType: %T", src)
	}
	return nil
}

type NullAlertIncidentEntityType struct {
	AlertIncidentEntityType AlertIncidentEntityType `json:"alert_incident_entity_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if AlertIncidentEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertIncidentEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertIncidentEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertIncidentEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertIncidentEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertIncidentEntityType), nil
}

type AlertIncidentStatus string

const (
	AlertIncidentStatusOpen     AlertIncidentStatus = "open"
	AlertIncidentStatusResolved AlertIncidentStatus = "resolved"
)

func (e *AlertIncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertIncidentStatus(s)
	case string:
		*e = AlertIncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertIncidentStatus: %T", src)
	}
	return nil
}

type NullAlertIncidentStatus struct {
	AlertIncidentStatus AlertIncidentStatus `json:"alert_incident_status"`
	Valid               bool                `json:"valid"` // Valid is true if AlertIncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertIncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertIncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertIncidentStatus), nil
}

type AlertSignalType string

const (
	AlertSignalTypeErrorRate                  AlertSignalType = "error_rate"
	AlertSignalTypeLatencyP95Ms               AlertSignalType = "latency_p95_ms"
	AlertSignalTypeLatencyP99Ms               AlertSignalType = "latency_p99_ms"
	AlertSignalTypeApdex                      AlertSignalType = "apdex"
	AlertSignalTypeThroughputPerMin           AlertSignalType = "throughput_per_min"
	AlertSignalTypeAvailabilityPercent        AlertSignalType = "availability_percent"
	AlertSignalTypeHostCpuUtilization         AlertSignalType = "host_cpu_utilization"
	AlertSignalTypeHostMemoryUtilization      AlertSignalType = "host_memory_utilization"
	AlertSignalTypeHostFilesystemUtilization  AlertSignalType = "host_filesystem_utilization"
	AlertSignalTypeHostReportingStale         AlertSignalType = "host_reporting_stale"
	AlertSignalTypeContainerCpuUtilization    AlertSignalType = "container_cpu_utilization"
	AlertSignalTypeContainerMemoryUtilization AlertSignalType = "container_memory_utilization"
	AlertSignalTypeContainerReportingStale    AlertSignalType = "container_reporting_stale"
)

func (e *AlertSignalType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSignalType(s)
	case string:
		*e = AlertSignalType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSignalType: %T", src)
	}
	return nil
}

type NullAlertSignalType struct {
	AlertSignalType AlertSignalType `json:"alert_signal_type"`
	Valid           bool            `json:"valid"` // Valid is true if AlertSignalType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSignalType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSignalType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSignalType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSignalType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSignalType), nil
}

type BillingPlan string

const (
	BillingPlanStarter    BillingPlan = "starter"
	BillingPlanPro        BillingPlan = "pro"
	BillingPlanEnterprise BillingPlan = "enterprise"
)

func (e *BillingPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPlan(s)
	case string:
		*e = BillingPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPlan: %T", src)
	}
	return nil
}

type NullBillingPlan struct {
	BillingPlan BillingPlan `json:"billing_plan"`
	Valid       bool        `json:"valid"` // Valid is true if BillingPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPlan) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPlan), nil
}

type BillingStatus string

const (
	BillingStatusTrialing BillingStatus = "trialing"
	BillingStatusActive   BillingStatus = "active"
	BillingStatusPastDue  BillingStatus = "past_due"
)

func (e *BillingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingStatus(s)
	case string:
		*e = BillingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingStatus: %T", src)
	}
	return nil
}

type NullBillingStatus struct {
	BillingStatus BillingStatus `json:"billing_status"`
	Valid         bool          `json:"valid"` // Valid is true if BillingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BillingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingStatus), nil
}

type DeploymentCorrelationStrategy string

const (
	DeploymentCorrelationStrategyTimeWindow     DeploymentCorrelationStrategy = "time_window"
	DeploymentCorrelationStrategyExplicitID     DeploymentCorrelationStrategy = "explicit_id"
	DeploymentCorrelationStrategyServiceVersion DeploymentCorrelationStrategy = "service_version"
)

func (e *DeploymentCorrelationStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentCorrelationStrategy(s)
	case string:
		*e = DeploymentCorrelationStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentCorrelationStrategy: %T", src)
	}
	return nil
}

type NullDeploymentCorrelationStrategy struct {
	DeploymentCorrelationStrategy DeploymentCorrelationStrategy `json:"deployment_correlation_strategy"`
	Valid                         bool                          `json:"valid"` // Valid is true if DeploymentCorrelationStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentCorrelationStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentCorrelationStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentCorrelationStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentCorrelationStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentCorrelationStrategy), nil
}

type DeploymentStatus string

const (
	DeploymentStatusPending    DeploymentStatus = "pending"
	DeploymentStatusInProgress DeploymentStatus = "in_progress"
	DeploymentStatusSucceeded  DeploymentStatus = "succeeded"
	DeploymentStatusFailed     DeploymentStatus = "failed"
	DeploymentStatusRolledBack DeploymentStatus = "rolled_back"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus `json:"deployment_status"`
	Valid            bool             `json:"valid"` // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type HeartbeatMonitorStatus string

const (
	HeartbeatMonitorStatusHealthy       HeartbeatMonitorStatus = "healthy"
	HeartbeatMonitorStatusGrace         HeartbeatMonitorStatus = "grace"
	HeartbeatMonitorStatusMissed        HeartbeatMonitorStatus = "missed"
	HeartbeatMonitorStatusNeverReceived HeartbeatMonitorStatus = "never_received"
)

func (e *HeartbeatMonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HeartbeatMonitorStatus(s)
	case string:
		*e = HeartbeatMonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HeartbeatMonitorStatus: %T", src)
	}
	return nil
}

type NullHeartbeatMonitorStatus struct {
	HeartbeatMonitorStatus HeartbeatMonitorStatus `json:"heartbeat_monitor_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if HeartbeatMonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHeartbeatMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HeartbeatMonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HeartbeatMonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHeartbeatMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HeartbeatMonitorStatus), nil
}

type IngestionKeyKind string

const (
	IngestionKeyKindPublic  IngestionKeyKind = "public"
	IngestionKeyKindPrivate IngestionKeyKind = "private"
)

func (e *IngestionKeyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IngestionKeyKind(s)
	case string:
		*e = IngestionKeyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for IngestionKeyKind: %T", src)
	}
	return nil
}

type NullIngestionKeyKind struct {
	IngestionKeyKind IngestionKeyKind `json:"ingestion_key_kind"`
	Valid            bool             `json:"valid"` // Valid is true if IngestionKeyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIngestionKeyKind) Scan(value interface{}) error {
	if value == nil {
		ns.IngestionKeyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IngestionKeyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIngestionKeyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IngestionKeyKind), nil
}

type NotificationDeliveryStatus string

const (
	NotificationDeliveryStatusPending   NotificationDeliveryStatus = "pending"
	NotificationDeliveryStatusSucceeded NotificationDeliveryStatus = "succeeded"
	NotificationDeliveryStatusFailed    NotificationDeliveryStatus = "failed"
)

func (e *NotificationDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationDeliveryStatus(s)
	case string:
		*e = NotificationDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationDeliveryStatus: %T", src)
	}
	return nil
}

type NullNotificationDeliveryStatus struct {
	NotificationDeliveryStatus NotificationDeliveryStatus `json:"notification_delivery_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if NotificationDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationDeliveryStatus), nil
}

type NotificationDestinationKind string

const (
	NotificationDestinationKindWebhook NotificationDestinationKind = "webhook"
	NotificationDestinationKindEmail   NotificationDestinationKind = "email"
)

func (e *NotificationDestinationKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationDestinationKind(s)
	case string:
		*e = NotificationDestinationKind(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationDestinationKind: %T", src)
	}
	return nil
}

type NullNotificationDestinationKind struct {
	NotificationDestinationKind NotificationDestinationKind `json:"notification_destination_kind"`
	Valid                       bool                        `json:"valid"` // Valid is true if NotificationDestinationKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationDestinationKind) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationDestinationKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationDestinationKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationDestinationKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationDestinationKind), nil
}

type NotificationEventType string

const (
	NotificationEventTypeHeartbeatmissed    NotificationEventType = "heartbeat.missed"
	NotificationEventTypeHeartbeatrecovered NotificationEventType = "heartbeat.recovered"
	NotificationEventTypeDestinationtest    NotificationEventType = "destination.test"
)

func (e *NotificationEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationEventType(s)
	case string:
		*e = NotificationEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationEventType: %T", src)
	}
	return nil
}

type NullNotificationEventType struct {
	NotificationEventType NotificationEventType `json:"notification_event_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if NotificationEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationEventType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationEventType), nil
}

type NotificationSourceKind string

const (
	NotificationSourceKindHeartbeat NotificationSourceKind = "heartbeat"
)

func (e *NotificationSourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationSourceKind(s)
	case string:
		*e = NotificationSourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationSourceKind: %T", src)
	}
	return nil
}

type NullNotificationSourceKind struct {
	NotificationSourceKind NotificationSourceKind `json:"notification_source_kind"`
	Valid                  bool                   `json:"valid"` // Valid is true if NotificationSourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationSourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationSourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationSourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationSourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationSourceKind), nil
}

type PgbossJobState string

const (
	PgbossJobStateCreated   PgbossJobState = "created"
	PgbossJobStateRetry     PgbossJobState = "retry"
	PgbossJobStateActive    PgbossJobState = "active"
	PgbossJobStateCompleted PgbossJobState = "completed"
	PgbossJobStateCancelled PgbossJobState = "cancelled"
	PgbossJobStateFailed    PgbossJobState = "failed"
)

func (e *PgbossJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PgbossJobState(s)
	case string:
		*e = PgbossJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for PgbossJobState: %T", src)
	}
	return nil
}

type NullPgbossJobState struct {
	PgbossJobState PgbossJobState `json:"pgboss_job_state"`
	Valid          bool           `json:"valid"` // Valid is true if PgbossJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPgbossJobState) Scan(value interface{}) error {
	if value == nil {
		ns.PgbossJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PgbossJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPgbossJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PgbossJobState), nil
}

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           pgtype.Text      `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	IDToken               pgtype.Text      `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type AlertDeliveryAttempt struct {
	ID            string              `json:"id"`
	AppID         string              `json:"app_id"`
	DestinationID string              `json:"destination_id"`
	RuleID        pgtype.Text         `json:"rule_id"`
	IncidentID    pgtype.Text         `json:"incident_id"`
	EventID       pgtype.Text         `json:"event_id"`
	EventType     AlertEventType      `json:"event_type"`
	Payload       []byte              `json:"payload"`
	Status        AlertDeliveryStatus `json:"status"`
	AttemptNumber int32               `json:"attempt_number"`
	NextAttemptAt pgtype.Timestamp    `json:"next_attempt_at"`
	LastAttemptAt pgtype.Timestamp    `json:"last_attempt_at"`
	DeliveredAt   pgtype.Timestamp    `json:"delivered_at"`
	HttpStatus    pgtype.Int4         `json:"http_status"`
	ErrorMessage  pgtype.Text         `json:"error_message"`
	CreatedAt     pgtype.Timestamp    `json:"created_at"`
	UpdatedAt     pgtype.Timestamp    `json:"updated_at"`
}

type AlertEvent struct {
	ID            string           `json:"id"`
	AppID         string           `json:"app_id"`
	RuleID        pgtype.Text      `json:"rule_id"`
	IncidentID    pgtype.Text      `json:"incident_id"`
	EventType     AlertEventType   `json:"event_type"`
	WindowStartAt pgtype.Timestamp `json:"window_start_at"`
	WindowEndAt   pgtype.Timestamp `json:"window_end_at"`
	ObservedValue pgtype.Float4    `json:"observed_value"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type AlertIncident struct {
	ID                string                  `json:"id"`
	AppID             string                  `json:"app_id"`
	RuleID            string                  `json:"rule_id"`
	Status            AlertIncidentStatus     `json:"status"`
	OpenedAt          pgtype.Timestamp        `json:"opened_at"`
	ResolvedAt        pgtype.Timestamp        `json:"resolved_at"`
	LastObservedAt    pgtype.Timestamp        `json:"last_observed_at"`
	LastObservedValue pgtype.Float4           `json:"last_observed_value"`
	LastNotifiedAt    pgtype.Timestamp        `json:"last_notified_at"`
	RenotifyCount     int32                   `json:"renotify_count"`
	CreatedAt         pgtype.Timestamp        `json:"created_at"`
	UpdatedAt         pgtype.Timestamp        `json:"updated_at"`
	EntityType        AlertIncidentEntityType `json:"entity_type"`
	EntityID          string                  `json:"entity_id"`
	EntityName        pgtype.Text             `json:"entity_name"`
}

type AlertRule struct {
	ID                         string           `json:"id"`
	AppID                      string           `json:"app_id"`
	Name                       string           `json:"name"`
	SignalType                 AlertSignalType  `json:"signal_type"`
	Comparator                 AlertComparator  `json:"comparator"`
	Threshold                  float32          `json:"threshold"`
	WindowMinutes              int32            `json:"window_minutes"`
	RenotifyMinutes            pgtype.Int4      `json:"renotify_minutes"`
	ApdexTargetMs              pgtype.Int4      `json:"apdex_target_ms"`
	ScopeServicesInclude       []string         `json:"scope_services_include"`
	ScopeServicesExclude       []string         `json:"scope_services_exclude"`
	ScopeSpanNamesInclude      []string         `json:"scope_span_names_include"`
	ScopeSpanNamesExclude      []string         `json:"scope_span_names_exclude"`
	ScopeEnvironmentsInclude   []string         `json:"scope_environments_include"`
	ScopeEnvironmentsExclude   []string         `json:"scope_environments_exclude"`
	ScopeScopesInclude         []string         `json:"scope_scopes_include"`
	ScopeScopesExclude         []string         `json:"scope_scopes_exclude"`
	IsEnabled                  bool             `json:"is_enabled"`
	LastTriggeredAt            pgtype.Timestamp `json:"last_triggered_at"`
	LastResolvedAt             pgtype.Timestamp `json:"last_resolved_at"`
	NextEvaluationAt           pgtype.Timestamp `json:"next_evaluation_at"`
	LastEvaluatedAt            pgtype.Timestamp `json:"last_evaluated_at"`
	EvaluationLeaseToken       pgtype.Text      `json:"evaluation_lease_token"`
	EvaluationLeaseExpiresAt   pgtype.Timestamp `json:"evaluation_lease_expires_at"`
	CreatedBy                  pgtype.Text      `json:"created_by"`
	UpdatedBy                  pgtype.Text      `json:"updated_by"`
	CreatedAt                  pgtype.Timestamp `json:"created_at"`
	UpdatedAt                  pgtype.Timestamp `json:"updated_at"`
	ScopeHostNamesInclude      []string         `json:"scope_host_names_include"`
	ScopeHostNamesExclude      []string         `json:"scope_host_names_exclude"`
	ScopeContainerNamesInclude []string         `json:"scope_container_names_include"`
	ScopeContainerNamesExclude []string         `json:"scope_container_names_exclude"`
}

type AlertRuleDestination struct {
	RuleID        string           `json:"rule_id"`
	DestinationID string           `json:"destination_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type AlertWebhookDestination struct {
	ID               string           `json:"id"`
	AppID            string           `json:"app_id"`
	Name             string           `json:"name"`
	Url              string           `json:"url"`
	HeadersEncrypted string           `json:"headers_encrypted"`
	IsEnabled        bool             `json:"is_enabled"`
	LastTestedAt     pgtype.Timestamp `json:"last_tested_at"`
	CreatedBy        pgtype.Text      `json:"created_by"`
	UpdatedBy        pgtype.Text      `json:"updated_by"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type App struct {
	ID                         string           `json:"id"`
	OrganizationID             string           `json:"organization_id"`
	Name                       string           `json:"name"`
	CreatedBy                  pgtype.Text      `json:"created_by"`
	UpdatedBy                  pgtype.Text      `json:"updated_by"`
	LogsFirstReceivedAt        pgtype.Timestamp `json:"logs_first_received_at"`
	TracesFirstReceivedAt      pgtype.Timestamp `json:"traces_first_received_at"`
	MetricsFirstReceivedAt     pgtype.Timestamp `json:"metrics_first_received_at"`
	DeploymentsFirstReceivedAt pgtype.Timestamp `json:"deployments_first_received_at"`
	CreatedAt                  pgtype.Timestamp `json:"created_at"`
	UpdatedAt                  pgtype.Timestamp `json:"updated_at"`
	HeartbeatsFirstReceivedAt  pgtype.Timestamp `json:"heartbeats_first_received_at"`
}

type AssistantChat struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	AppID          string           `json:"app_id"`
	Title          string           `json:"title"`
	CreatedBy      pgtype.Text      `json:"created_by"`
	UpdatedBy      pgtype.Text      `json:"updated_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type AssistantMessage struct {
	ID        string           `json:"id"`
	ChatID    string           `json:"chat_id"`
	Position  int32            `json:"position"`
	Role      string           `json:"role"`
	Content   string           `json:"content"`
	Parts     []byte           `json:"parts"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type DashboardLogView struct {
	ID         string           `json:"id"`
	AppID      string           `json:"app_id"`
	Slug       string           `json:"slug"`
	Name       string           `json:"name"`
	Definition []byte           `json:"definition"`
	CreatedBy  pgtype.Text      `json:"created_by"`
	UpdatedBy  pgtype.Text      `json:"updated_by"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type Deployment struct {
	ID                    string                        `json:"id"`
	AppID                 string                        `json:"app_id"`
	ServiceName           string                        `json:"service_name"`
	EnvironmentName       string                        `json:"environment_name"`
	Version               pgtype.Text                   `json:"version"`
	Status                DeploymentStatus              `json:"status"`
	StartedAt             pgtype.Timestamp              `json:"started_at"`
	FinishedAt            pgtype.Timestamp              `json:"finished_at"`
	GitSha                pgtype.Text                   `json:"git_sha"`
	GitBranch             pgtype.Text                   `json:"git_branch"`
	GitRepository         pgtype.Text                   `json:"git_repository"`
	GitActor              pgtype.Text                   `json:"git_actor"`
	CommitMessage         pgtype.Text                   `json:"commit_message"`
	ExternalUrl           pgtype.Text                   `json:"external_url"`
	CorrelationStrategy   DeploymentCorrelationStrategy `json:"correlation_strategy"`
	DeploymentIDAttribute pgtype.Text                   `json:"deployment_id_attribute"`
	ServiceVersion        pgtype.Text                   `json:"service_version"`
	Metadata              []byte                        `json:"metadata"`
	CreatedAt             pgtype.Timestamp              `json:"created_at"`
	UpdatedAt             pgtype.Timestamp              `json:"updated_at"`
}

type HeartbeatMonitor struct {
	ID                   string                 `json:"id"`
	AppID                string                 `json:"app_id"`
	Name                 string                 `json:"name"`
	Token                string                 `json:"token"`
	ExpectedEverySeconds int32                  `json:"expected_every_seconds"`
	GraceSeconds         int32                  `json:"grace_seconds"`
	LastCheckInAt        pgtype.Timestamp       `json:"last_check_in_at"`
	LastStatus           HeartbeatMonitorStatus `json:"last_status"`
	LastMissedAt         pgtype.Timestamp       `json:"last_missed_at"`
	LastRecoveredAt      pgtype.Timestamp       `json:"last_recovered_at"`
	CreatedBy            pgtype.Text            `json:"created_by"`
	UpdatedBy            pgtype.Text            `json:"updated_by"`
	CreatedAt            pgtype.Timestamp       `json:"created_at"`
	UpdatedAt            pgtype.Timestamp       `json:"updated_at"`
	PausedAt             pgtype.Timestamp       `json:"paused_at"`
}

type HeartbeatMonitorDestination struct {
	HeartbeatMonitorID string           `json:"heartbeat_monitor_id"`
	DestinationID      string           `json:"destination_id"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type IngestionKey struct {
	ID         string           `json:"id"`
	AppID      string           `json:"app_id"`
	Kind       IngestionKeyKind `json:"kind"`
	Key        string           `json:"key"`
	CreatedBy  pgtype.Text      `json:"created_by"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	RevokedAt  pgtype.Timestamp `json:"revoked_at"`
}

type Invitation struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	Email          string           `json:"email"`
	Role           pgtype.Text      `json:"role"`
	Status         string           `json:"status"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	InviterID      string           `json:"inviter_id"`
}

type Member struct {
	ID             string           `json:"id"`
	OrganizationID string           `json:"organization_id"`
	UserID         string           `json:"user_id"`
	Role           string           `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type NotificationDelivery struct {
	ID            string                     `json:"id"`
	AppID         string                     `json:"app_id"`
	DestinationID string                     `json:"destination_id"`
	SourceKind    NotificationSourceKind     `json:"source_kind"`
	SourceID      string                     `json:"source_id"`
	EventType     NotificationEventType      `json:"event_type"`
	Payload       []byte                     `json:"payload"`
	Status        NotificationDeliveryStatus `json:"status"`
	AttemptNumber int32                      `json:"attempt_number"`
	NextAttemptAt pgtype.Timestamp           `json:"next_attempt_at"`
	LastAttemptAt pgtype.Timestamp           `json:"last_attempt_at"`
	DeliveredAt   pgtype.Timestamp           `json:"delivered_at"`
	HttpStatus    pgtype.Int4                `json:"http_status"`
	ErrorMessage  pgtype.Text                `json:"error_message"`
	CreatedAt     pgtype.Timestamp           `json:"created_at"`
	UpdatedAt     pgtype.Timestamp           `json:"updated_at"`
}

type NotificationDestination struct {
	ID                      string                      `json:"id"`
	AppID                   string                      `json:"app_id"`
	Name                    string                      `json:"name"`
	Kind                    NotificationDestinationKind `json:"kind"`
	IsEnabled               bool                        `json:"is_enabled"`
	WebhookUrl              pgtype.Text                 `json:"webhook_url"`
	WebhookHeadersEncrypted pgtype.Text                 `json:"webhook_headers_encrypted"`
	EmailRecipients         []string                    `json:"email_recipients"`
	CreatedBy               pgtype.Text                 `json:"created_by"`
	UpdatedBy               pgtype.Text                 `json:"updated_by"`
	CreatedAt               pgtype.Timestamp            `json:"created_at"`
	UpdatedAt               pgtype.Timestamp            `json:"updated_at"`
}

type Organization struct {
	ID               string            `json:"id"`
	Name             string            `json:"name"`
	Slug             string            `json:"slug"`
	Logo             pgtype.Text       `json:"logo"`
	StripeCustomerID pgtype.Text       `json:"stripe_customer_id"`
	BillingEmail     pgtype.Text       `json:"billing_email"`
	BillingPlan      NullBillingPlan   `json:"billing_plan"`
	BillingStatus    NullBillingStatus `json:"billing_status"`
	CreatedAt        pgtype.Timestamp  `json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `json:"updated_at"`
}

type OrganizationActivation struct {
	OrganizationID       string           `json:"organization_id"`
	HasViewedTelemetry   bool             `json:"has_viewed_telemetry"`
	HasCreatedFirstAlert bool             `json:"has_created_first_alert"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type OrganizationUsage struct {
	ID                   string           `json:"id"`
	OrganizationID       string           `json:"organization_id"`
	LogsRetentionDays    int32            `json:"logs_retention_days"`
	TracesRetentionDays  int32            `json:"traces_retention_days"`
	MetricsRetentionDays int32            `json:"metrics_retention_days"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	LogsIngestedBytes    int64            `json:"logs_ingested_bytes"`
	TracesIngestedBytes  int64            `json:"traces_ingested_bytes"`
	MetricsIngestedBytes int64            `json:"metrics_ingested_bytes"`
	IngestLimitBytes     int64            `json:"ingest_limit_bytes"`
	Notified70At         pgtype.Timestamp `json:"notified_70_at"`
	Notified85At         pgtype.Timestamp `json:"notified_85_at"`
	Notified100At        pgtype.Timestamp `json:"notified_100_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type PgbossJob struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Priority        int32              `json:"priority"`
	Data            []byte             `json:"data"`
	State           PgbossJobState     `json:"state"`
	RetryLimit      int32              `json:"retry_limit"`
	RetryCount      int32              `json:"retry_count"`
	RetryDelay      int32              `json:"retry_delay"`
	RetryBackoff    bool               `json:"retry_backoff"`
	RetryDelayMax   pgtype.Int4        `json:"retry_delay_max"`
	ExpireSeconds   int32              `json:"expire_seconds"`
	DeletionSeconds int32              `json:"deletion_seconds"`
	SingletonKey    pgtype.Text        `json:"singleton_key"`
	SingletonOn     pgtype.Timestamp   `json:"singleton_on"`
	GroupID         pgtype.Text        `json:"group_id"`
	GroupTier       pgtype.Text        `json:"group_tier"`
	StartAfter      pgtype.Timestamptz `json:"start_after"`
	CreatedOn       pgtype.Timestamptz `json:"created_on"`
	StartedOn       pgtype.Timestamptz `json:"started_on"`
	CompletedOn     pgtype.Timestamptz `json:"completed_on"`
	KeepUntil       pgtype.Timestamptz `json:"keep_until"`
	Output          []byte             `json:"output"`
	DeadLetter      pgtype.Text        `json:"dead_letter"`
	Policy          pgtype.Text        `json:"policy"`
}

type PgbossQueue struct {
	Name             string      `json:"name"`
	Policy           string      `json:"policy"`
	RetryLimit       int32       `json:"retry_limit"`
	RetryDelay       int32       `json:"retry_delay"`
	RetryBackoff     bool        `json:"retry_backoff"`
	RetryDelayMax    pgtype.Int4 `json:"retry_delay_max"`
	ExpireSeconds    int32       `json:"expire_seconds"`
	RetentionSeconds int32       `json:"retention_seconds"`
	DeletionSeconds  int32       `json:"deletion_seconds"`
	DeadLetter       pgtype.Text `json:"dead_letter"`
	Partition        bool        `json:"partition"`
	TableName        string      `json:"table_name"`
}

type Session struct {
	ID                   string           `json:"id"`
	ExpiresAt            pgtype.Timestamp `json:"expires_at"`
	Token                string           `json:"token"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	IpAddress            pgtype.Text      `json:"ip_address"`
	UserAgent            pgtype.Text      `json:"user_agent"`
	UserID               string           `json:"user_id"`
	ActiveOrganizationID pgtype.Text      `json:"active_organization_id"`
}

type Subscription struct {
	ID                   string           `json:"id"`
	Plan                 string           `json:"plan"`
	ReferenceID          string           `json:"reference_id"`
	TrialStart           pgtype.Timestamp `json:"trial_start"`
	TrialEnd             pgtype.Timestamp `json:"trial_end"`
	StripeCustomerID     pgtype.Text      `json:"stripe_customer_id"`
	StripeSubscriptionID pgtype.Text      `json:"stripe_subscription_id"`
	Status               string           `json:"status"`
	PeriodStart          pgtype.Timestamp `json:"period_start"`
	PeriodEnd            pgtype.Timestamp `json:"period_end"`
	CancelAtPeriodEnd    bool             `json:"cancel_at_period_end"`
	CancelAt             pgtype.Timestamp `json:"cancel_at"`
	CanceledAt           pgtype.Timestamp `json:"canceled_at"`
	EndedAt              pgtype.Timestamp `json:"ended_at"`
	Seats                pgtype.Int4      `json:"seats"`
	BillingInterval      pgtype.Text      `json:"billing_interval"`
	StripeScheduleID     pgtype.Text      `json:"stripe_schedule_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID               string           `json:"id"`
	Name             string           `json:"name"`
	Email            string           `json:"email"`
	EmailVerified    bool             `json:"email_verified"`
	Image            pgtype.Text      `json:"image"`
	StripeCustomerID pgtype.Text      `json:"stripe_customer_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
