// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pgdb

import (
	"context"
)

type Querier interface {
	GetActiveIngestionKeyByKey(ctx context.Context, key string) (GetActiveIngestionKeyByKeyRow, error)
	GetAppRetentionPolicy(ctx context.Context, id string) (GetAppRetentionPolicyRow, error)
	GetBillingState(ctx context.Context, referenceID string) (GetBillingStateRow, error)
	GetHeartbeatMonitorByToken(ctx context.Context, token string) (GetHeartbeatMonitorByTokenRow, error)
	GetOrganizationUsageForUpdate(ctx context.Context, organizationID string) (OrganizationUsage, error)
	InsertPgBossJob(ctx context.Context, arg InsertPgBossJobParams) (string, error)
	MarkAppHeartbeatsFirstReceived(ctx context.Context, arg MarkAppHeartbeatsFirstReceivedParams) error
	MarkAppLogsFirstReceived(ctx context.Context, id string) error
	MarkAppMetricsFirstReceived(ctx context.Context, id string) error
	MarkAppTracesFirstReceived(ctx context.Context, id string) error
	MarkHeartbeatMonitorHealthy(ctx context.Context, arg MarkHeartbeatMonitorHealthyParams) error
	TouchIngestionKeyLastUsed(ctx context.Context, id string) error
	UpdateOrganizationUsage(ctx context.Context, arg UpdateOrganizationUsageParams) error
}

var _ Querier = (*Queries)(nil)
