import fs from 'node:fs/promises';
import path from 'node:path';

const EMAILS_DIR = path.resolve('src/lib/server/email');
const OUTPUT_FILE = path.resolve('src/lib/server/email/email.generated.ts');

type TemplateInfo = {
	fileName: string;
	templateId: string;
	functionName: string;
	inputTypeName: string;
	placeholders: string[];
	raw: string;
};

const toPascalCase = (value: string): string => {
	return value
		.replace(/\.[^/.]+$/, '')
		.split(/[^a-zA-Z0-9]+/g)
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
};

const escapeTemplateLiteral = (value: string): string => {
	return value.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
};

const extractPlaceholders = (template: string): string[] => {
	const re = /\{\{\s*([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\}\}/g;
	const found = new Set<string>();

	for (const match of template.matchAll(re)) {
		if (match[1]) {
			found.add(match[1]);
		}
	}

	return [...found].sort((left, right) => left.localeCompare(right));
};

const getTemplates = async (): Promise<TemplateInfo[]> => {
	const entries = await fs.readdir(EMAILS_DIR, { withFileTypes: true });
	const templates: TemplateInfo[] = [];

	for (const entry of entries) {
		if (!entry.isFile() || !entry.name.endsWith('.html')) {
			continue;
		}

		const filePath = path.join(EMAILS_DIR, entry.name);
		const raw = await fs.readFile(filePath, 'utf8');
		const templateId = entry.name.replace(/\.html$/i, '');
		const base = toPascalCase(entry.name);

		templates.push({
			fileName: entry.name,
			templateId,
			functionName: `render${base}Email`,
			inputTypeName: `Render${base}Input`,
			placeholders: extractPlaceholders(raw),
			raw
		});
	}

	return templates.sort((left, right) => left.fileName.localeCompare(right.fileName));
};

const buildGeneratedFile = (templates: TemplateInfo[]): string => {
	const lines: string[] = [];
	lines.push("// Code generated by `pnpm email:generate`. DO NOT EDIT.");
	lines.push('');

	for (const template of templates) {
		if (template.placeholders.length === 0) {
			lines.push(`type ${template.inputTypeName} = Record<string, never>;`);
		} else {
			lines.push(`type ${template.inputTypeName} = {`);
			for (const key of template.placeholders) {
				lines.push(`\t${key}: string;`);
			}
			lines.push('};');
		}
		lines.push('');

		const escaped = escapeTemplateLiteral(template.raw);
		const interpolated = escaped.replace(
			/\{\{\s*([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\}\}/g,
			(_match, name: string) => `\${input.${name}}`
		);

		lines.push(`function ${template.functionName}(input: ${template.inputTypeName}): string {`);
		lines.push(`\treturn \`${interpolated}\`;`);
		lines.push('}');
		lines.push('');
	}

	lines.push('const templates = {');
	for (const template of templates) {
		lines.push(`\t"${template.templateId}": ${template.functionName},`);
	}
	lines.push('} as const;');
	lines.push('');

	lines.push('type TemplateMap = {');
	for (const template of templates) {
		lines.push(`\t"${template.templateId}": ${template.inputTypeName};`);
	}
	lines.push('};');
	lines.push('');

	lines.push('type Template = {');
	lines.push('\t[K in keyof TemplateMap]: {');
	lines.push('\t\ttemplate: K;');
	lines.push('\t\tprops: TemplateMap[K];');
	lines.push('\t};');
	lines.push('}[keyof TemplateMap];');
	lines.push('');

	lines.push('export {');
	for (const template of templates) {
		lines.push(`\t${template.functionName},`);
	}
	lines.push('\ttemplates,');
	lines.push('};');
	lines.push('');

	lines.push('export type {');
	for (const template of templates) {
		lines.push(`\t${template.inputTypeName},`);
	}
	lines.push('\tTemplate,');
	lines.push('};');
	lines.push('');

	return lines.join('\n');
};

const main = async () => {
	const templates = await getTemplates();
	if (templates.length === 0) {
		throw new Error(`No .html templates found in ${EMAILS_DIR}`);
	}

	const out = buildGeneratedFile(templates);
	await fs.writeFile(OUTPUT_FILE, out, 'utf8');
	console.log(
		`Generated ${path.relative(process.cwd(), OUTPUT_FILE)} from ${templates.length} template(s).`
	);
};

await main();
