// Code generated by `pnpm email:generate`. DO NOT EDIT.

type RenderBillingSubscriptionCompletedInput = {
	organizationName: string;
	planName: string;
};

function renderBillingSubscriptionCompletedEmail(input: RenderBillingSubscriptionCompletedInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Thanks for subscribing to Orvo for ${input.organizationName}. You're all set.</p>
  <p>Your ${input.planName} plan is now active for the current billing period, so you can get back to shipping with logs, metrics, and traces flowing in one place.</p>
  <p>If you haven't already, this is a good time to connect your app and invite the rest of your team.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. If anything looks off in billing, just reply to this email and we'll help sort it out.</p>
</body>

</html>
`;
}

type RenderBillingTrialExpiredInput = {
	organizationName: string;
};

function renderBillingTrialExpiredEmail(input: RenderBillingTrialExpiredInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} has ended.</p>
  <p>To keep your team monitoring apps without interruption, add a payment method from the billing page and we'll restore access right away.</p>
  <p>If you're still evaluating Orvo and need a hand deciding on a plan, reply to this email and we'll help you figure out the right fit.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. The sooner you update billing, the sooner you can get back to full access.</p>
</body>

</html>
`;
}

type RenderBillingTrialStartedInput = {
	organizationName: string;
	trialEnd: string;
};

function renderBillingTrialStartedEmail(input: RenderBillingTrialStartedInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} is now active, and you're ready to start exploring.</p>
  <p>Your trial runs until ${input.trialEnd}, so now is the perfect time to connect an app, send some telemetry, and see Orvo in action.</p>
  <p>If you have questions while getting set up, reply to this email and we'll help you get moving.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. The more real traffic you send during the trial, the better sense you'll get of how Orvo fits your workflow.</p>
</body>

</html>
`;
}

type RenderBillingTrialWillEndInput = {
	organizationName: string;
	trialEnd: string;
};

function renderBillingTrialWillEndEmail(input: RenderBillingTrialWillEndInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} is ending soon.</p>
  <p>It wraps up on ${input.trialEnd}, so if you'd like to keep access going, head to billing and add a payment method before the deadline.</p>
  <p>If you're close but not fully set up yet, reply to this email and we'll help you get the most out of the rest of your trial.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. A quick billing update now means no interruption once the trial ends.</p>
</body>

</html>
`;
}

type RenderOtpInput = {
	code: string;
	purpose: string;
};

function renderOtpEmail(input: RenderOtpInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>We got a request for your ${input.purpose} verification code. You'll need this:</p>

  <h2>
    ${input.code}
  </h2>
  <p>If you didn't ask for this, just ignore the email. No worries.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. This code expires in 10 minutes, so be quick!</p>
</body>

</html>
`;
}

const templates = {
	"billing-subscription-completed": renderBillingSubscriptionCompletedEmail,
	"billing-trial-expired": renderBillingTrialExpiredEmail,
	"billing-trial-started": renderBillingTrialStartedEmail,
	"billing-trial-will-end": renderBillingTrialWillEndEmail,
	"otp": renderOtpEmail,
} as const;

type TemplateMap = {
	"billing-subscription-completed": RenderBillingSubscriptionCompletedInput;
	"billing-trial-expired": RenderBillingTrialExpiredInput;
	"billing-trial-started": RenderBillingTrialStartedInput;
	"billing-trial-will-end": RenderBillingTrialWillEndInput;
	"otp": RenderOtpInput;
};

type Template = {
	[K in keyof TemplateMap]: {
		template: K;
		props: TemplateMap[K];
	};
}[keyof TemplateMap];

const renderTemplate = (input: Template): string => {
	switch (input.template) {
		case "billing-subscription-completed":
			return renderBillingSubscriptionCompletedEmail(input.props);
		case "billing-trial-expired":
			return renderBillingTrialExpiredEmail(input.props);
		case "billing-trial-started":
			return renderBillingTrialStartedEmail(input.props);
		case "billing-trial-will-end":
			return renderBillingTrialWillEndEmail(input.props);
		case "otp":
			return renderOtpEmail(input.props);
	}
};

export {
	renderBillingSubscriptionCompletedEmail,
	renderBillingTrialExpiredEmail,
	renderBillingTrialStartedEmail,
	renderBillingTrialWillEndEmail,
	renderOtpEmail,
	renderTemplate,
	templates,
};

export type {
	RenderBillingSubscriptionCompletedInput,
	RenderBillingTrialExpiredInput,
	RenderBillingTrialStartedInput,
	RenderBillingTrialWillEndInput,
	RenderOtpInput,
	Template,
};
