// Code generated by `pnpm email:generate`. DO NOT EDIT.

type RenderOtpInput = {
	code: string;
	purpose: string;
};

const renderOtpEmail = (input: RenderOtpInput): string => {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>We got a request for your ${input.purpose} verification code. You'll need this:</p>

  <h2>
    ${input.code}
  </h2>
  <p>If you didn't ask for this, just ignore the email. No worries.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. This code expires in 10 minutes, so be quick!</p>
</body>

</html>`;
};

const templates = {
	otp: renderOtpEmail
} as const;

type TemplateMap = {
	otp: RenderOtpInput;
};

type Template = {
	[K in keyof TemplateMap]: {
		template: K;
		props: TemplateMap[K];
	};
}[keyof TemplateMap];

export { renderOtpEmail, templates };
export type { RenderOtpInput, Template };
