// Code generated by `pnpm email:generate`. DO NOT EDIT.

type RenderBillingTrialExpiredInput = {
	organizationName: string;
};

function renderBillingTrialExpiredEmail(input: RenderBillingTrialExpiredInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} has ended.</p>
  <p>Add a payment method from the billing page to restore access.</p>
  <p>Cheers,<br />The Orvo team</p>
</body>

</html>
`;
}

type RenderBillingTrialStartedInput = {
	organizationName: string;
	trialEnd: string;
};

function renderBillingTrialStartedEmail(input: RenderBillingTrialStartedInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} is now active.</p>
  <p>Trial end: ${input.trialEnd}</p>
  <p>Cheers,<br />The Orvo team</p>
</body>

</html>
`;
}

type RenderBillingTrialWillEndInput = {
	organizationName: string;
	trialEnd: string;
};

function renderBillingTrialWillEndEmail(input: RenderBillingTrialWillEndInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>Your Orvo trial for ${input.organizationName} is ending soon.</p>
  <p>Trial end: ${input.trialEnd}</p>
  <p>Cheers,<br />The Orvo team</p>
</body>

</html>
`;
}

type RenderOtpInput = {
	code: string;
	purpose: string;
};

function renderOtpEmail(input: RenderOtpInput): string {
	return `<!DOCTYPE html>
<html>

<body>
  <p>Hey there,</p>
  <p>We got a request for your ${input.purpose} verification code. You'll need this:</p>

  <h2>
    ${input.code}
  </h2>
  <p>If you didn't ask for this, just ignore the email. No worries.</p>
  <p>Cheers,<br />The Orvo team</p>
  <p>P.S. This code expires in 10 minutes, so be quick!</p>
</body>

</html>
`;
}

const templates = {
	"billing-trial-expired": renderBillingTrialExpiredEmail,
	"billing-trial-started": renderBillingTrialStartedEmail,
	"billing-trial-will-end": renderBillingTrialWillEndEmail,
	"otp": renderOtpEmail,
} as const;

type TemplateMap = {
	"billing-trial-expired": RenderBillingTrialExpiredInput;
	"billing-trial-started": RenderBillingTrialStartedInput;
	"billing-trial-will-end": RenderBillingTrialWillEndInput;
	"otp": RenderOtpInput;
};

type Template = {
	[K in keyof TemplateMap]: {
		template: K;
		props: TemplateMap[K];
	};
}[keyof TemplateMap];

export {
	renderBillingTrialExpiredEmail,
	renderBillingTrialStartedEmail,
	renderBillingTrialWillEndEmail,
	renderOtpEmail,
	templates,
};

export type {
	RenderBillingTrialExpiredInput,
	RenderBillingTrialStartedInput,
	RenderBillingTrialWillEndInput,
	RenderOtpInput,
	Template,
};
